### ISSUE TITLE
Why did Former2 try to CreateServiceLinkedRole

### ISSUE THREAD

**Issue by payne911** [iann0036/former2#117]
After pressing ``Scan``, two API calls appeared in ``CloudTrail``:

1)  `SearchProvisionedProducts`, which seems legit to me.
2) The one below. One second after the first one.

![image](https://user-images.githubusercontent.com/38117856/95494695-47c2d180-096c-11eb-9bd9-570ba9af19d0.png)

Why exactly did it try to do that?

Also, this was ultimately generated after selecting `Include all Resources` (see the typo with ` ${IAMGroup}istrative`):

```yaml
  IAMServiceLinkedRole2:
    Type: "AWS::IAM::ServiceLinkedRole"
    Properties:
      AWSServiceName: "support.amazonaws.com"
      Description: !Sub "Enables resource access for ${EC2PrefixList.OwnerId} to provide billing, ${IAMGroup}istrative and support services"
```
