### ISSUE TITLE
Error in code generated for AWS::KMS::Alias

### ISSUE THREAD

**Issue by gomibushi** [iann0036/former2#156]
Code generated is like this:
```
  KMSAlias:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aliasname"
      TargetKeyId: !Ref KMSKey
```
Should be like this:
```
  KMSAlias:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: "alias/aliasname"
      TargetKeyId: !Ref KMSKey
```
Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-alias.html
