### ISSUE TITLE
DockerVolumeConfiguration vs EFSVolumeConfiguration

### ISSUE THREAD

**Issue by gvasquez95** [iann0036/former2#165]
Today we had an issue with Former2 misinterpreting an ECS volume mount, adding it to the template under DockerVolumeConfiguration (which only works on EC2) for a Fargate service and, what was the proper element was EFSVolumeConfiguration. What info should I provide to assist in debugging and correcting the wrong behaviour?

**Comment by iann0036** [comment]
Hey @gvasquez95,

Apologies for the late response. If you provide what you received vs. what you expected to receive, that should suffice to help me implement the change.

**Comment by gvasquez95** [comment]
This issue appeared once again with this output from Former2:

```
                DockerVolumeConfiguration:
                    AuthorizationConfig:
                        IAM: "DISABLED"
                    FilesystemId: "fs-xxxxxxxx"
                    RootDirectory: "/3/"
                    TransitEncryption: "DISABLED"
```

**Comment by gvasquez95** [comment]
And something like this works fine:
```
                EFSVolumeConfiguration: 
                    AuthorizationConfig: 
                        IAM: "DISABLED"
                    FilesystemId: "fs-xxxxxxxx"
                    RootDirectory: "/state"
                    TransitEncryption: "DISABLED"
```
