### ISSUE TITLE
Illegal !Sub sequences

### ISSUE THREAD

**Issue by mbenz89** [iann0036/former2#174]
Hi! I am using Former2 Cli to create a cloudformation template which I try to read with AWS CDK afterward. The CDK reports an error about a strange looking `!Sub` sequence:

```
    ApiGatewayStage:
        Type: "AWS::ApiGateway::Stage"
        Properties:
            StageName: !Ref ApiGatewayStage2
            DeploymentId: !Ref ApiGatewayDeployment6
            RestApiId: !Ref ApiGatewayRestApi6
            CacheClusterEnabled: false
            Variables: {}
            TracingEnabled: false

    ApiGatewayStage2:
        Type: "AWS::ApiGateway::Stage"
        Properties:
            StageName: !Ref ApiGatewayStage3
            DeploymentId: !Ref ApiGatewayDeployment
            RestApiId: !Ref ApiGatewayRestApi4
            CacheClusterEnabled: false
            Variables: {}
            TracingEnabled: false
            Tags: 
              - 
                Key: "aws:cloudformation:logical-id"
                Value: !Sub "MainApi${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGatewayStage12}12}12}12}12}12}12}12}12}12}11}11}11}11}11}11}11}11}11}11}10}10}10}10}10}10}10}10}10}10}9}9}9}9}9}9}9}9}9}9}8}8}8}8}8}8}8}8}8}8}7}7}7}7}7}7}7}7}7}7}3}Stage"
              - 
                Key: "aws:cloudformation:stack-id"
                Value: "arn:aws:cloudformation:eu-central-1:217096764149:stack/backend-js-dev/1b02cd70-f51c-11eb-b73c-0644bfa5fad4"
              - 
                Key: "aws:cloudformation:stack-name"
                Value: "backend-js-dev"

    ApiGatewayStage3:
        Type: "AWS::ApiGateway::Stage"
        Properties:
            StageName: !Ref ApiGatewayStage4
            DeploymentId: !Ref ApiGatewayDeployment5
            RestApiId: !Ref ApiGatewayRestApi5
            CacheClusterEnabled: false
            Variables: {}
            TracingEnabled: false
            Tags: 
              - 
                Key: "aws:cloudformation:logical-id"
                Value: !Sub "MainApi${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGateway${ApiGatewayStage12}12}12}12}12}12}12}12}12}12}11}11}11}11}11}11}11}11}11}11}10}10}10}10}10}10}10}10}10}10}9}9}9}9}9}9}9}9}9}9}8}8}8}8}8}8}8}8}8}8}7}7}7}7}7}7}7}7}7}7}4}Stage"
              - 
                Key: "aws:cloudformation:stack-id"
                Value: "arn:aws:cloudformation:eu-central-1:217096764149:stack/backend-mb-dev/c1c9a5b0-00f8-11ec-abe9-06081d79189e"
              - 
                Key: "aws:cloudformation:stack-name"
                Value: "backend-mb-dev"
```

As you see, the Tags contain these super long substitution patterns (`Value: !Sub "MainApi${ApiGateway${ApiGateway${ApiGateway${ApiGateway$...`)

As a temporary fix, I disabled the loops here:
https://github.com/iann0036/former2/blob/master/js/mappings.js#L578, https://github.com/iann0036/former2/blob/master/js/mappings.js#L597, https://github.com/iann0036/former2/blob/master/js/mappings.js#L614

That seems to work as the Tags are properly set now.

I do not understand the logic of these loops and guess that this is not a proper fix and will lead to issues elsewhere. Can you help with a proper fix?
