### ISSUE TITLE
`AWS::QuickSight::Analysis` resource is missing details

### ISSUE THREAD

**Issue by moltar** [iann0036/former2#202]
First of all, amazing project and a huge time saver. Many thanks! 🙇🏼‍♂️ 

---

It appears that `AWS::QuickSight::Analysis` resource is not reversing correctly.

Here's what I get after running:

```sh
npx former2 generate \
  --output-cloudformation "quicksight.yml" \
  --services "QuickSight" \
  --sort-output
```

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    QuickSightAnalysis:
        Type: "AWS::QuickSight::Analysis"
        Properties:
            AnalysisId: ...
            Name: ...
            AwsAccountId: ...
```

_(Some info snipped out for privacy)_

It is missing the meat & potatoes - the actual definition of the analysis. Only contains the shell above.

Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-analysis.html

---

Other resources, such as `AWS::QuickSight::DataSet` and `AWS::QuickSight::DataSource` come back filled out.

**Comment by moltar** [comment]
Noticed a similar issue for `AWS::QuickSight::Dashboard`:

```yaml
    QuickSightDashboard:
        Type: "AWS::QuickSight::Dashboard"
        Properties:
            DashboardId: ...
            Name: ...
            AwsAccountId: ...
```

Also just the high-level definition is created, but no details.
