### ISSUE TITLE
Cloudfront - ResponseHeadersPolicy missing in generated code

### ISSUE THREAD

**Issue by andriibu-ownid** [iann0036/former2#206]
There is cloudfront distribution with custom response headers policy which I can see in Former2 UI
![respheadpolicy1](https://user-images.githubusercontent.com/5993355/144573831-9b93381a-277c-46ef-b484-60417955c1fd.png)

But I can't see the same in generated yaml:
```
DefaultCacheBehavior: 
    AllowedMethods: 
      - "HEAD"
      - "GET"
    CachedMethods: 
      - "HEAD"
      - "GET"
    Compress: false
    CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
    SmoothStreaming: false
    TargetOriginId: "DefaultOrigin"
    ViewerProtocolPolicy: "redirect-to-https"
```

Would be great to add support of it.
