### ISSUE TITLE
Import of Dynamo table fails with "Property AttributeName cannot be empty." error.

### ISSUE THREAD

**Issue by BigDataDaddy** [iann0036/former2#229]
First time trying import.  Trying to create a stack and import a single Dynamo table into it.   So, after scanning my account I select the 1 Dynamo table from it, generate a template for it, and try to import it into CloudFormation.

Former2 shows that the change set gets created and that the change set executes correctly as shown in the following screen snip from Former2: 
![image](https://user-images.githubusercontent.com/13018379/164546895-361135ed-f06d-4bc3-b1d3-ba6eac3fc9fd.png)

However, when looking in CloudFormation for the stack I see that the change set for the stack failed as shown in the following screen snip from the CloudFormation console:
![image](https://user-images.githubusercontent.com/13018379/164547263-5014fc78-f7a9-4096-9fd1-1dfd7417ddfb.png)

Is this a bug or am I doing something wrong?

**Comment by iann0036** [comment]
Hi @BigDataDaddy,

Thanks for raising!

This is most likely a bug on our end, I suspect somewhere around the TTL Expiry property. Could you paste the generated CloudFormation template, as well as the "Raw Output (Debug)" responses here so we can track it down? Be careful to remove anything sensitive before pasting also.

**Comment by BigDataDaddy** [comment]
Thanks for such a quick reply Ian.   I really love what you're doing in this repo and several others.  I'll post that info, redacted if necessary, shorty.

**Comment by BigDataDaddy** [comment]
Here's the generated CF template: 

```
AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    DynamoDBTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions: 
              - 
                AttributeName: "LockID"
                AttributeType: "S"
            TableName: "<redacted_table_name>"
            KeySchema: 
              - 
                AttributeName: "LockID"
                KeyType: "HASH"
            ProvisionedThroughput: 
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
            TimeToLiveSpecification: 
                Enabled: false

```
