### ISSUE TITLE
SecurityGroup and its related SecurityGroups (ingress/egress)

### ISSUE THREAD

**Issue by LouWii** [iann0036/former2#242]
Hi,

First of all, thanks @iann0036. Former 2 is making my life easier, it's a really great tool!

I use the "Related Resources" option to easily find out how resources are linked together. I was wondering why Former 2 does not indicate the related SecurityGroups that can be found in ingress/egress entries. Is that a limitation on AWS?

For example, if I export `sg-EEEE4444`:

```
AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    EC2SecurityGroup:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "Prod Web"
            GroupName: "prod-web-sg"
            VpcId: "vpc-xxxxx"
            SecurityGroupIngress: 
              - 
                SourceSecurityGroupId: "sg-AAAA1234"
                SourceSecurityGroupOwnerId: !Ref AWS::AccountId
                FromPort: 80
                IpProtocol: "tcp"
                ToPort: 80
```

I would expect Former 2 to tell me that `sg-AAAA1234` is a related resource of `sg-EEEE4444` and ask me if I want to include it in the export.
