### ISSUE TITLE
Dumping S3 resource

### ISSUE THREAD

**Issue by jorgeviana** [iann0036/former2#267]
Hi, I'm using Former2 for the first time here.
I was expecting that the dump for a S3 bucket would show the entire configuration of the bucket, including for example the Bucket Policy and permissions, but I get the below example.
It seems to me that if I use output of Former2 I will not create exactly the same resource.
Am I doing something wrong, or is this expected behaviour?

Here's an example of what I get 
```
AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    S3Bucket:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: "my-hello-to-the-world"
            WebsiteConfiguration: 
                IndexDocument: "index.html"
                ErrorDocument: "error.html"
```
