### ISSUE TITLE
RDSParameterGroupName not populeated in Cfn

### ISSUE THREAD

**Issue by dritz-ecloud** [iann0036/former2#278]
In the Web GUI, RDS->Parameter Groups-> [] -> DBParameterGroupName is displayed.
However, this field never makes it into the generated CloudFormation.

Possibly related, Former2 isn't replacing the RDS::DBInstance property `DBParameterGroupName` with the corresponding RDS::DBParameterGroup name.  

This is the Parameter Group (named prod-corpsys):
```
RDSDBParameterGroup17:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: Parameter group for prod-corpsys
      Family: mysql5.6
      Parameters:
        connect_timeout: '31536000'
        delayed_insert_timeout: '31536000'
        ...
```
Referencing RDS Instance:
```
  RDSDBInstance18:
    Type: AWS::RDS::DBInstance
    Properties:
...
      DBSubnetGroupName: prod-corpsys
...
```

Thanks for taking a look.
