### ISSUE TITLE
CloudFormation template with weird usage of !Sub

### ISSUE THREAD

**Issue by nowak-ninja** [iann0036/former2#300]
Hi, I am playing with former2-cli and I have found in my almost 2k lines template, there is weird usage of !Sub functions pointing to resource.Version trying to replace all instances of "1" and "6" characters, example:

```
Resources:
(...)
    EC2VPCCidrBlock:
        Type: "AWS::EC2::VPCCidrBlock"
        Properties:
            CidrBlock: !Sub "${EC2PrefixList.Version}0.xxx.xx.0/2${EC2PrefixList2.Version}"
            VpcId: !Ref EC2VPC
(...)
    EC2PrefixList:
        Type: "AWS::EC2::PrefixList"
        Properties:
            AddressFamily: "IPv4"
            PrefixListName: "corporate-network-CIDRs"
            MaxEntries: 10
            Tags: 
              - 
                Key: "Name"
                Value: "IT Network 1-Servers"
            Entries: 
              - 
                Cidr: "10.0.0.0/8"
                Description: "IT Network 1"
    EC2PrefixList2:
        Type: "AWS::EC2::PrefixList"
        Properties:
            AddressFamily: "IPv4"
            PrefixListName: "XXX-CNI-Ranges-For-VPN-Routing"
            MaxEntries: 50
            Entries: 
              - 
                Cidr: !Sub "${EC2PrefixList.Version}0.3.xx.0/22"
                Description: "XXXX"
(...)
```

There are 271 instances of ${EC2PrefixList.Version} in the template.
