### ISSUE TITLE
AWS::Transfer::User should use `!GetAtt <Server>.ServerId` not `!Ref <Server>`

### ISSUE THREAD

**Issue by jackvreeken** [iann0036/former2#329]
Currently this code is generated for Users:

```YAML
    TransferUser:
        Type: "AWS::Transfer::User"
        Properties:
            ServerId: !Ref TransferServer
```

The `!Ref TransferServer` should instead be `!GetAtt TransferServer.ServerId`.

According to the docs, the ServerId field in TransferUser expects something that matches `Pattern: ^s-([0-9a-f]{17})$`. 
According to TransferServer docs, `!Ref` returns something like `arn:aws:transfer:us-east-1:123456789012:server/s-01234567890abcdef`, whereas the GetAtt.ServerId returns something like `s-01234567890abcdef`.
