### ISSUE TITLE
docker-compose.yml binding to privileged port

### ISSUE THREAD

**Issue by marafa-sugarcrm** [iann0036/former2#347]
the docker-compose.yml is attempting to bind to a priviledged port (80)
all ports below 1024 are priviledged, 
instead we can use 8080 like so
```
version: '3'
services:
  former2:
    image: nginx:stable-alpine
    ports:
      - "127.0.0.1:8080:80"
    volumes:
    - .:/usr/share/nginx/html

```
