### ISSUE TITLE
Yaml CFN  VS. Mixed CFN in Yaml with inline JSON

### ISSUE THREAD

**Issue by kisst** [iann0036/former2#387]
Current behaviour is that for json policy documents  are kept in json with either `|` or just inline.
For example current:
```
    IAMRole:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/"
            RoleName: "BedrockStudioProvisioningRole"
            AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"datazone.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
            MaxSessionDuration: 3600
 ```
 or  if the policy is too big then:
 ```
     IAMPolicy2:
        Type: "AWS::IAM::Policy"
        Properties:
            PolicyDocument: |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
...
etc
```

Neither above are pretty, a consistent native yaml would be at least my preference so even if this wouldn't be the default, at least a flag would be great.
for example:
```
ype: AWS::IAM::Role
Properties:
  RoleName: BedrockStudioServiceRole
  AssumeRolePolicyDocument:
    Version: '2012-10-17'
    Statement:
      - Effect: Allow
        Principal:
          Service: datazone.amazonaws.com
        Action: sts:AssumeRole
  Policies:
    - PolicyName: BedrockStudioServiceRolePolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - bedrock:*
              - iam:PassRole
            Resource: '*'
```
