### ISSUE TITLE
Escape regex in cloudformation, for backslash

### ISSUE THREAD

**Issue by officeguy** [iann0036/former2#40]
firstly, great tool, thanks for making it.

secondly, an enhancement request. When generating the cloud formation yaml from my API Gateway resource, any regex needs to be properly escaped if it contains the backslash character. Currently it generates an error during import [ import done via Cloud Formation into another AWS account].

original value was in an Authorizer, in the field Token Validation:
```
^Bearer [-0-9a-zA-z\.]*$
```

example of former2 generated code [run locally ]
```
Resources:
  apigateway03da9b1:
    Properties:
      IdentityValidationExpression: "^Bearer [-0-9a-zA-z\.]*$"
```

manually corrected code, by adding an additional backslash
```
Resources:
  apigateway03da9b1:
    Properties:
      IdentityValidationExpression: "^Bearer [-0-9a-zA-z\\.]*$"      
```

doc reference
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-regexes.html

"Since AWS CloudFormation templates use the JSON syntax for specifying objects and data, you will need to add an additional backslash to any backslash characters in your regular expression, or JSON will interpret these as escape characters."
thanks

**Comment by iann0036** [comment]
Hi there,

Thanks soo much for raising!

I've pushed a fix to escape all backslashes if they appear in a single line string property, so that should cover all fields with this issue.

Seems to work for me, but please re-raise if you still see this issue anywhere.

**Comment by officeguy** [comment]
thanks. it may need the scope to be reduced however, as it has overly escaped another line.

previous working code:
```
Resources:
    iamea8e77f:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/service-role/"
            RoleName: "myapp-crud-get-role-1xz7qabc"
            AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
            MaxSessionDuration: 3600

```

and newly broken code with too many backslashes:

```
Resources:
    iamea8e77f:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/service-role/"
            RoleName: "myapp-crud-get-role-1xz7qabc"
            AssumeRolePolicyDocument: "{\\"Version\\":\\"2012-10-17\\",\\"Statement\\":[{\\"Effect\\":\\"Allow\\",\\"Principal\\":{\\"Service\\":\\"lambda.amazonaws.com\\"},\\"Action\\":\\"sts:AssumeRole\\"}]}"
            MaxSessionDuration: 3600
```

**Comment by officeguy** [comment]
also fyi status code values from api gateway also affected.  ref:

```
            Integration: 
                CacheNamespace: "mhvgiz"
                IntegrationResponses: 
                  - 
                    ResponseParameters: 
                        method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,access-control-allow-origin,userid'"
                        method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST,PUT,PATCH,DELETE'"
                        method.response.header.Access-Control-Allow-Origin: "'*'"
                    StatusCode: "200"
                PassthroughBehavior: "WHEN_NO_MATCH"
                RequestTemplates: 
                    application/json: "{\\"statusCode\\": 200}"

```

should be:
```
 application/json: "{\"statusCode\": 200}"
```
