### ISSUE TITLE
UsagePlan output failing to parse CloudFormation

### ISSUE THREAD

**Issue by rainabba** [iann0036/former2#49]
AWS::ApiGateway::UsagePlan.Properties.ApiStages[].Throttle is provided as the following YAML which fails to parse in the CloudFormation Editor with: `Cannot convert the template because of an error:: unidentified alias "/*:"`

Provided and fails:
```
                Throttle: 
                    */*: 
                        BurstLimit: 240
                        RateLimit: 120
```

Edited and works:
```
                Throttle: 
                    BurstLimit: 240
                    RateLimit: 120
```

If I remove the `*/*:` line and indent the Limit values accordingly, it parses fine.
