### ISSUE TITLE
AWS::RDS::DBCluster ScalingConfiguration doesn't support TimeoutAction

### ISSUE THREAD

**Issue by rainabba** [iann0036/former2#50]
I've exported a DBCluster which includes the following **`ScalingConfiguration`** that throws an error because **`TimeoutAction`** isn't supported.

The template snippet of interest is
```YAML
            ScalingConfiguration: 
                MinCapacity: 8
                MaxCapacity: 256
                AutoPause: false
                SecondsUntilAutoPause: 3600
                TimeoutAction: "RollbackCapacityChange"
```

It is not supported in ScalingConfiguration per this doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbcluster-scalingconfiguration.html

I do see that option with the create-db-cluster CLI command: https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-cluster.html

I can also see that Ruby's API supports it: https://docs.aws.amazon.com/sdkforruby/api/Aws/RDS/Types/ScalingConfigurationInfo.html

I don't see any sign of that option being supported through CloudFormation at all right now.
