### ISSUE TITLE
Incorrect types for some VPC resource properties

### ISSUE THREAD

**Issue by reidca** [iann0036/former2#58]
I have cfn-lint installed for VSCode and after loading the template that former2 generated the following warnings were shown:

E3012: Property Resources/CustomerGateway/Properties/BgpAsn should be of type Integer
E3012: Property Resources/ec2b729b8b/Properties/Protocol should be of type Integer
E3034: Value has to be between 1 and 32766 at Resources/ec29e8c64b/Properties/RuleNumber

Relevant snippet of template:

```
ec29e8c64b:
        Type: "AWS::EC2::NetworkAclEntry"
        Properties:
            CidrBlock: "0.0.0.0/0"
            Egress: true
            NetworkAclId: !Ref NetworkAcl1
            Protocol: "-1"
            RuleAction: "deny"
            RuleNumber: 32767
```
