### ISSUE TITLE
Option to add Retention policy for generated resources

### ISSUE THREAD

**Issue by reidca** [iann0036/former2#59]
I believe one of the strong user cases for former2 is being able to generate templates of manually created resources that can then be imported into CloudFormation using the new Import existing resource feature.

In order to do this, the template you use has to have a retention policy on each of the resources.

e.g.
  ```
VPC:
        Type: "AWS::EC2::VPC"
        DeletionPolicy: Retain
        Properties:
            CidrBlock: "10.1.0.0/16"
            EnableDnsSupport: true
            EnableDnsHostnames: true
            InstanceTenancy: "default"
```

If there was an option in Former2 to add that when generating the CloudFormation template that would take away a lot of manual work!
