### ISSUE TITLE
gp2 volumes bring 'iops' setting incorrectly.

### ISSUE THREAD

**Issue by alytle** [iann0036/former2#6]
The AWS API shows the "iops" setting for gp2 volumes, which of course is a calculation and not a user settable value. When I imported some EC2 volumes, I got the "Iops" value in Cloudformation, which is invalid as they are gp2 types.

I also got SnapshotId values of null, when the key/value pair should be omitted for volumes not being created from a snapshot.

```
  Volume:
    Type: "AWS::EC2::Volume"
    Properties:
      Iops: 600
      Size: 200
      VolumeType: "gp2"
      SnapshotId: ""
```
